# Abyss Configuration File
# See: http://dev.bukkit.org/server-mods/abyss/pages/configuration/

auto-update: true
entity-type-whitelist:
  - Item
  - XPOrb
  - Painting
  - Arrow
  - Snowball
  - Fireball
  - SmallFireball
  - ThrownEnderpearl
  - EyeOfEnderSignal
  - ThrownExpBottle
  - ItemFrame
  - WitherSkull
  - PrimedTnt
  - FallingSand
  - FireworksRocketEntity
  - Minecart
  - Boat
  - Creeper
  - Skeleton
  - Spider
  - Giant
  - Zombie
  - Slime
  - Ghast
  - PigZombie
  - Enderman
  - CaveSpider
  - Silverfish
  - Blaze
  - LavaSlime
  - EnderDragon
  - WitherBoss
  - Bat
  - Witch
  - Pig
  - Sheep
  - Cow
  - Chicken
  - Squid
  - Wolf
  - MushroomCow
  - SnowMan
  - Ozelot
  - VillagerGolem
  - EnderCrystal
  - SPLASH_POTION
  - EGG
use-worldguard: true


wand-name: Portal Wand
wand-material: STICK
wand-range: 256


network-key: SKULL ITEM:3
network-color: WHITE


minimum-depth: 2
minimum-size: 2
maximum-size: 4


use-portal-effect: true
portal-effect: mobspawner flames
portal-sound: enderman teleport
use-static-effect: true
static-effect-centered: false
static-effect-full-height: true
static-sound:
    name: portal
    volume: 0.2
    pitch: 1


single-material: false
corner-depth: 1
frame-materials: occluding


minimum-velocity: 0.15
maximum-velocity: 10


cooldown-ticks: 40
smart-rails: true


limit-distance: true
base-range: 50
depth-multiplier: 25
