name: Abyss
version: 5
description: A water-based portal system for players.
author: Stendec <me@stendec.me>

main: me.stendec.abyss.AbyssPlugin
softdepend: [WorldGuard, Vault]

commands:
    abyss:
        description: The main command for all Abyss commands.
        usage: /<command> [subcommand]
        permission: abyss.command.base

permissions:
    abyss.*:
        description: Gives access to all of Abyss.
        children:
            abyss.modifiers.*: true
            abyss.use: true

    abyss.use:
        description: Allows you to travel through a portal.
        default: true

    abyss.moderate:
        description: Allows you to manipulate the portals of other players.
        default: op

    abyss.update:
        description: Allows you to see update notices for Abyss.
        default: op

    abyss.modifiers.*:
        description: Gives access to all Abyss modifiers.
        children:
            abyss.modifiers.bed: true
            abyss.modifiers.compass: true

    abyss.modifiers.bed:
        description: Allows you to use the Bed portal modifier.
        default: op
    abyss.modifiers.compass:
        description: Allows you to use the Compass portal modifier.
        default: op
    abyss.modifiers.emerald_block:
        description: Allows you to use the Emerald Block modifier.
        default: op
    abyss.modifiers.exp_bottle:
        description: Allows you to use the Bottle o' Enchanting modifier.
        default: op

    abyss.detail.*:
        description: Gives access to all portal details.
        children:
            abyss.detail.uuid: true
            abyss.detail.distance: true
            abyss.detail.location: true

    abyss.detail.uuid:
        description: Allows you to see a portal's UUID.
        default: op
    abyss.detail.distance:
        description: Allows you to see precise portal distances.
        default: op
    abyss.detail.location:
        description: Allows you to see precise portal locations.
        default: op


    abyss.command.*:
        description: Gives access to all Abyss commands.
        children:
            abyss.command.base: true
            abyss.command.configure: true
            abyss.command.create: true
            abyss.command.delete: true
            abyss.command.info: true
            abyss.command.list: true
            abyss.command.modifier: true
            abyss.command.reload: true
            abyss.command.teleport: true
            abyss.command.wand: true

    abyss.command.base:
        description: Gives access to the /abyss command.
        default: op

    abyss.command.configure:
        description: Sets portal configuration.
        default: op
    abyss.command.create:
        description: Creates a new portal at the target location.
        default: op
    abyss.command.delete:
        description: Deletes the target portal.
        default: op
    abyss.command.info:
        description: Displays information on the target portal.
        default: true
    abyss.command.list:
        description: Displays a list of portals.
        default: op
    abyss.command.modifier:
        description: Set configuration on a portal's modifiers.
        default: op
    abyss.command.reload:
        description: Reload's Abyss's configuration.
        default: op
    abyss.command.teleport:
        description: Gives access to the Teleport command.
        default: op
    abyss.command.teleport_other:
        description: Allows you to teleport someone else with the Teleport command.
        default: op
    abyss.command.update:
        description: Allows you to update Abyss via command.
        default: op
    abyss.command.wand:
        description: Gives access to the Wand command.
        default: true
